import type { Metadata } from "next";
import "./globals.css";
import Header from "./component/Head";
import Banner from "./component/Banner"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="min-h-screen flex flex-col">
        <Banner/>
        <main className="flex-grow container mx-auto px-4 py-6">{children}</main>
      </body>
    </html>
  );
}
